# Example dephy-messaging-network-auth configuration

global:
  permission:
    read: true
    write: true
    # ttl: 300 # The ttl field is optional and defaults to 300 seconds

# Each entry defines a pubkey with read/write permissions, the ttl field is optional
# To enable whitelist mode, set the global permissions to false and add accessible permissions below
permissions:
  - pubkey: "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
    read: true
    write: true
    ttl: 3600
