services:
  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dephy
      POSTGRES_PASSWORD: dephy
      POSTGRES_DB: dephy_messaging_network
    shm_size: ${POSTGRESQL_SHM_SIZE:-128mb}
    command: >
      -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ${POSTGRESQL_CONFIG_FILE:-./postgresql.conf}:/etc/postgresql/postgresql.conf
      - postgresql_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  default-pgbouncer:
    image: bitnami/pgbouncer:1.24.0
    restart: always
    depends_on:
      - postgresql
    environment:
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_USERNAME: dephy
      POSTGRESQL_PASSWORD: dephy
      PGBOUNCER_DATABASE: dephy_messaging_network
      PGBOUNCER_MAX_CLIENT_CONN: ${PGBOUNCER_MAX_CLIENT_CONN:-120}
      PGBOUNCER_DEFAULT_POOL_SIZE: ${PGBOUNCER_DEFAULT_POOL_SIZE:-20}
      PGBOUNCER_RESERVE_POOL_SIZE: ${PGBOUNCER_RESERVE_POOL_SIZE:-0}
      PGBOUNCER_RESERVE_POOL_TIMEOUT: ${PGBOUNCER_RESERVE_POOL_TIMEOUT:-5}
      PGBOUNCER_SERVER_IDLE_TIMEOUT: ${PGBOUNCER_SERVER_IDLE_TIMEOUT:-600}
      PGBOUNCER_SERVER_CONNECT_TIMEOUT: ${PGBOUNCER_SERVER_CONNECT_TIMEOUT:-15}
      PGBOUNCER_POOL_MODE: transaction

  publisher-pgbouncer:
    image: bitnami/pgbouncer:1.24.0
    restart: always
    depends_on:
      - postgresql
    environment:
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_USERNAME: dephy
      POSTGRESQL_PASSWORD: dephy
      PGBOUNCER_DATABASE: dephy_messaging_network

  dephy-messaging-network-auth:
    image: dephyio/dephy-messaging-network-auth:${DEPHY_IMAGE_TAG:-latest}
    restart: always
    environment:
      RUST_LOG: ${ENV_RUST_LOG:-info,dephy_messaging_network_auth=info}
      RUST_BACKTRACE: "1"
      SENTRY_DSN: ${SENTRY_DSN}
    command: >
      serve
      --config /opt/dephy-messaging-network-auth/config.yml
      --api-addr 0.0.0.0:8100
    ports:
      - "0.0.0.0:8100:8100"
    volumes:
      - ${AUTH_CONFIG_FILE:-./auth-config.yml}:/opt/dephy-messaging-network-auth/config.yml

  dephy-messaging-network:
    image: dephyio/dephy-messaging-network:${DEPHY_IMAGE_TAG:-latest}
    restart: always
    depends_on:
      - default-pgbouncer
      - publisher-pgbouncer
    environment:
      RUST_LOG: ${ENV_RUST_LOG:-info,dephy_messaging_network=info}
      RUST_BACKTRACE: "1"
      SENTRY_DSN: ${SENTRY_DSN}
    command: >
      serve
      --pg-url 'postgresql://dephy:dephy@default-pgbouncer:6432/dephy_messaging_network'
      --publisher-pg-url 'postgresql://dephy:dephy@publisher-pgbouncer:6432/dephy_messaging_network'
      --db-max-write-connections "${DB_MAX_WRITE_CONNECTIONS:-10}"
      --db-max-read-connections "${DB_MAX_READ_CONNECTIONS:-10}"
      --api-addr '0.0.0.0:8000'
      --auth-service-url 'http://dephy-messaging-network-auth:8100'
      --key "${KEY}"
    ports:
      - "0.0.0.0:8000:8000"

  prometheus-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    restart: always
    depends_on:
      - postgresql
    environment:
      DATA_SOURCE_URI: "postgresql:5432/dephy_messaging_network?sslmode=disable"
      DATA_SOURCE_USER: dephy
      DATA_SOURCE_PASS: dephy
    command:
      - "--collector.stat_statements"
    ports:
      - "0.0.0.0:9187:9187"

  prometheus-pgbouncer-exporter:
    image: prometheuscommunity/pgbouncer-exporter:v0.10.2
    restart: always
    depends_on:
      - default-pgbouncer
    environment:
      PGBOUNCER_EXPORTER_CONNECTION_STRING: "postgres://dephy:dephy@default-pgbouncer:6432/pgbouncer?sslmode=disable"
    ports:
      - "0.0.0.0:9127:9127"

volumes:
  postgresql_data:
