global:
  scrape_interval: 15s

scrape_configs:
  - job_name: postgres
    static_configs:
      - targets: ["host.docker.internal:9187"]
  - job_name: node
    static_configs:
      - targets: ["host.docker.internal:9111"]
  - job_name: messaging_network
    static_configs:
      - targets: ["host.docker.internal:8000"]
