services:
  dephy-messaging-network:
    image: dephyio/dephy-messaging-network:${DEPHY_IMAGE_TAG:-latest}
    restart: always
    environment:
      RUST_LOG: ${ENV_RUST_LOG:-info,dephy_messaging_network=info}
      DEPHY_MN_AUTH_SERVICE_URL: ${DEPHY_MN_AUTH_SERVICE_URL}
      RUST_BACKTRACE: "1"
      SENTRY_DSN: ${SENTRY_DSN}
    ports:
      - "0.0.0.0:8000:8000"
    extra_hosts:
      host.docker.internal: host-gateway

  dephy-messaging-network-cleanup:
    image: dephyio/dephy-messaging-network:${DEPHY_IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      RUST_LOG: ${ENV_RUST_LOG:-info,dephy_messaging_network=info}
      RUST_BACKTRACE: "1"
      SENTRY_DSN: ${SENTRY_DSN}

  prometheus-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    restart: always
    command:
      - "--collector.stat_statements"
    ports:
      - "0.0.0.0:9187:9187"
