services:
  dephy-messaging-network-auth:
    extends:
      file: components.yml
      service: dephy-messaging-network-auth

  dephy-messaging-network:
    extends:
      file: components.yml
      service: dephy-messaging-network
    entrypoint: []
    command: >
      sh -c "
      /usr/bin/dephy-messaging-network serve
      --pg-url \"${DEPHY_MN_PG_URL}\"
      --publisher-pg-url 'postgresql://dephy:dephy@publisher-pgbouncer:6432/dephy_messaging_network'
      --db-max-write-connections \"${DEPHY_MN_DB_MAX_WRITE_CONNECTIONS:-10}\"
      --db-max-read-connections \"${DEPHY_MN_DB_MAX_READ_CONNECTIONS:-10}\"
      --api-addr '0.0.0.0:8000'
      $${DEPHY_MN_AUTH_SERVICE_URL:+--auth-service-url \"$DEPHY_MN_AUTH_SERVICE_URL\"}
      --key \"${DEPHY_MN_KEY}\"
      "

  dephy-messaging-network-cleanup:
    extends:
      file: components.yml
      service: dephy-messaging-network-cleanup
    command: >
      cleanup
      --pg-url '${DEPHY_MN_PG_URL}'

  prometheus-postgres-exporter:
    extends:
      file: components.yml
      service: prometheus-postgres-exporter
    environment:
      DATA_SOURCE_URI: "${PROMETHEUS_POSTGRES_EXPORTER_DATA_SOURCE_URI}"
      DATA_SOURCE_USER: "${PROMETHEUS_POSTGRES_EXPORTER_DATA_SOURCE_USER}"
      DATA_SOURCE_PASS: "${PROMETHEUS_POSTGRES_EXPORTER_DATA_SOURCE_PASS}"
