services:
  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dephy
      POSTGRES_PASSWORD: dephy
      POSTGRES_DB: dephy_messaging_network
    shm_size: ${POSTGRESQL_SHM_SIZE:-128mb}
    command: >
      -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ${POSTGRESQL_CONFIG_FILE:-./postgresql.conf}:/etc/postgresql/postgresql.conf
      - postgresql_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  dephy-messaging-network:
    image: dephyio/dephy-messaging-network:${DEPHY_IMAGE_TAG:-latest}
    restart: always
    depends_on:
      - postgresql
    environment:
      RUST_LOG: ${ENV_RUST_LOG:-info,dephy_messaging_network=info}
      RUST_BACKTRACE: "1"
    command: >
      serve
      --pg-url 'postgresql://dephy:dephy@postgresql:5432/dephy_messaging_network'
      --db-max-write-connections "${DB_MAX_WRITE_CONNECTIONS:-10}"
      --db-max-read-connections "${DB_MAX_READ_CONNECTIONS:-10}"
      --api-addr '0.0.0.0:8000'
    ports:
      - "0.0.0.0:8000:8000"

volumes:
  postgresql_data:
