services:
  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dephy
      POSTGRES_PASSWORD: dephy
      POSTGRES_DB: dephy_messaging_network
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  pgbouncer:
    image: bitnami/pgbouncer:1.24.0
    restart: always
    depends_on:
      - postgresql
    environment:
      POSTGRESQL_USERNAME: dephy
      POSTGRESQL_PASSWORD: dephy
      PGBOUNCER_DATABASE: dephy_messaging_network

  dephy-messaging-network:
    image: dephyio/dephy-messaging-network:master
    restart: always
    depends_on:
      - pgbouncer
    environment:
      RUST_LOG: "info,dephy_messaging_network=debug"
      RUST_BACKTRACE: "1"
    command: >
      serve
      --pg-url 'postgresql://dephy:dephy@pgbouncer:6432/dephy_messaging_network'
      --api-addr '0.0.0.0:8000'
    ports:
      - "0.0.0.0:8000:8000"

  prometheus-postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    restart: always
    depends_on:
      - postgresql
    environment:
      DATA_SOURCE_URI: "postgresql:5432/postgres?sslmode=disable"
      DATA_SOURCE_USER: dephy
      DATA_SOURCE_PASS: dephy
    ports:
      - "0.0.0.0:9187:9187"

  prometheus-pgbouncer-exporter:
    image: prometheuscommunity/pgbouncer-exporter:v0.10.2
    restart: always
    depends_on:
      - pgbouncer
    environment:
      PGBOUNCER_EXPORTER_CONNECTION_STRING: "postgres://dephy:dephy@pgbouncer:6432/pgbouncer?sslmode=disable"
    ports:
      - "0.0.0.0:9127:9127"

volumes:
  postgresql_data:
