services:
  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dephy
      POSTGRES_PASSWORD: dephy
      POSTGRES_DB: dephy_worker_archiver
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  api:
    image: dephyio/dephy-worker-registry:${DEPHY_IMAGE_TAG:-latest}
    restart: always
    depends_on:
      - postgresql
    environment:
      RUST_LOG: "info,dephy_worker_registry=debug"
      RUST_BACKTRACE: "1"
      SENTRY_DSN: ${SENTRY_DSN}
    entrypoint: "/usr/bin/dephy-worker-registry-api"
    command: >
      --pg-url 'postgresql://dephy:dephy@postgresql:5432/dephy_worker_archiver'
      --api-addr '0.0.0.0:9001'
      --worker-nostr-relay "${NOSTR_RELAY}"
      --pubkey "${REGISTRY_PUBKEY}"
    ports:
      - "0.0.0.0:9001:9001"

  poo-archiver:
    image: dephyio/dephy-worker-registry:${DEPHY_IMAGE_TAG:-latest}
    restart: always
    depends_on:
      - postgresql
    environment:
      RUST_LOG: "info,dephy_worker_registry=debug"
      RUST_BACKTRACE: "1"
      SENTRY_DSN: ${SENTRY_DSN}
    entrypoint: "/usr/bin/dephy-worker-registry-poo"
    command: >
      archive
      --pg-url 'postgresql://dephy:dephy@postgresql:5432/dephy_worker_archiver'
      --nostr-relay "${NOSTR_RELAY}"
      --pubkey "${REGISTRY_PUBKEY}"

volumes:
  postgresql_data:
