{
 "title": "Administrator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pg_instance", "query": { "query": "label_values(pg_up,instance)" } },
   {
    "name": "db",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{datname!~\"template.*|postgres\"},datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O (Bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (instance)",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m])) by (instance)",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions Per Minute (TPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "increase(db_id[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pending Events (Count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "db_pending_event", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$db\",instance=~\"$pg_instance\"}[$__rate_interval])) + sum(irate(pg_stat_database_xact_rollback{datname=~\"$db\",instance=~\"$pg_instance\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Database Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{instance=\"$pg_instance\", datname=\"$db\"}",
     "legendFormat": "max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Database Total Size",
   "type": "timeseries",
   "description": "Database Total Size ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"dephy_messaging_network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit)\n/\n(\n  sum(pg_stat_database_blks_hit)\n  + sum(pg_stat_database_blks_read)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$pg_instance\", datname=\"$db\"}[5m])",
     "legendFormat": "commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$pg_instance\", datname=\"$db\"}[5m])",
     "legendFormat": "rollbacks"
    }
   ]
  }
 ]
}