{
 "title": "Public Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Transactions Per Minute (TPM)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "increase(db_id[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pending Events (Count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "db_pending_event", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Connections (Count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "connections", "legendFormat": "__auto" }
   ]
  }
 ]
}