services:
  api:
    extends:
      file: components.yml
      service: api
    command: >
      serve
      --pg-url '${DEPHY_WR_PG_URL}'
      --api-addr '0.0.0.0:9000'
      --nostr-relay "${DEPHY_WR_NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --worker-nostr-relay "${DEPHY_WR_WORKER_NOSTR_RELAY:-ws://127.0.0.1:8000}"
      --key "${DEPHY_WR_KEY}"

  archiver:
    extends:
      file: components.yml
      service: daemon
    command: >
      archive
      --pg-url '${DEPHY_WR_PG_URL}'
      --nostr-relay "${DEPHY_WR_NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --key "${DEPHY_WR_KEY}"

  pinger:
    extends:
      file: components.yml
      service: daemon
    command: >
      ping
      --forever
      --pg-url '${DEPHY_WR_PG_URL}'
      --nostr-relay "${DEPHY_WR_NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --key "${DEPHY_WR_KEY}"

  ping-checker:
    extends:
      file: components.yml
      service: daemon
    command: >
      check_ping
      --forever
      --pg-url '${DEPHY_WR_PG_URL}'
      --nostr-relay "${DEPHY_WR_NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --key "${DEPHY_WR_KEY}"
