services:
  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dephy
      POSTGRES_PASSWORD: dephy
      POSTGRES_DB: dephy_worker_registry
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  api:
    extends:
      file: components.yml
      service: api
    depends_on:
      - postgresql
    command: >
      serve
      --pg-url 'postgresql://dephy:dephy@postgresql:5432/dephy_worker_registry'
      --api-addr '0.0.0.0:9000'
      --nostr-relay "${DEPHY_WR_NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --worker-nostr-relay "${DEPHY_WR_WORKER_NOSTR_RELAY:-ws://127.0.0.1:8000}"
      --key "${DEPHY_WR_KEY}"

  archiver:
    extends:
      file: components.yml
      service: daemon
    depends_on:
      - postgresql
    command: >
      archive
      --pg-url 'postgresql://dephy:dephy@postgresql:5432/dephy_worker_registry'
      --nostr-relay "${DEPHY_WR_NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --key "${DEPHY_WR_KEY}"

  pinger:
    extends:
      file: components.yml
      service: daemon
    depends_on:
      - postgresql
    command: >
      ping
      --forever
      --pg-url 'postgresql://dephy:dephy@postgresql:5432/dephy_worker_registry'
      --nostr-relay "${DEPHY_WR_NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --key "${DEPHY_WR_KEY}"

  ping-checker:
    extends:
      file: components.yml
      service: daemon
    depends_on:
      - postgresql
    command: >
      check_ping
      --forever
      --pg-url 'postgresql://dephy:dephy@postgresql:5432/dephy_worker_registry'
      --nostr-relay "${DEPHY_WR_NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --key "${DEPHY_WR_KEY}"

volumes:
  postgresql_data:
