services:
  api:
    image: dephyio/dephy-worker-registry:${DEPHY_IMAGE_TAG:-latest}
    restart: always
    environment:
      RUST_LOG: "info,dephy_worker_registry=debug"
      RUST_BACKTRACE: "1"
      SENTRY_DSN: ${SENTRY_DSN}
    ports:
      - "0.0.0.0:9002:9002"
    extra_hosts:
      host.docker.internal: host-gateway

  daemon:
    image: dephyio/dephy-worker-registry:${DEPHY_IMAGE_TAG:-latest}
    restart: always
    environment:
      RUST_LOG: "info,dephy_worker_registry=debug"
      RUST_BACKTRACE: "1"
      SENTRY_DSN: ${SENTRY_DSN}
    extra_hosts:
      host.docker.internal: host-gateway
