services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: dephy
      POSTGRES_PASSWORD: dephy
      POSTGRES_DB: dephy_worker_registry
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  pgbouncer:
    image: bitnami/pgbouncer:1.24.0
    depends_on:
      - postgresql
    environment:
      POSTGRESQL_USERNAME: dephy
      POSTGRESQL_PASSWORD: dephy
      PGBOUNCER_DATABASE: dephy_worker_registry

  api:
    image: dephyio/dephy-worker:master
    depends_on:
      - pgbouncer
    environment:
      RUST_LOG: "info,dephy_worker_registry=debug"
      RUST_BACKTRACE: "1"
    entrypoint: "/usr/bin/dephy-worker-registry-api"
    command: >
      --pg-url 'postgresql://dephy:dephy@pgbouncer:6432/dephy_worker_registry'
      --api-addr '0.0.0.0:8080'
      --worker-nostr-relay "${WORKER_NOSTR_RELAY:-ws://127.0.0.1:8000}"
      --key "${KEY}"
    ports:
      - "0.0.0.0:8080:8080"

  poo-archiver:
    image: dephyio/dephy-worker:master
    depends_on:
      - pgbouncer
    environment:
      RUST_LOG: "info,dephy_worker_registry=debug"
      RUST_BACKTRACE: "1"
    entrypoint: "/usr/bin/dephy-worker-registry-poo"
    extra_hosts:
      host.docker.internal: host-gateway
    command: >
      archive
      --pg-url 'postgresql://dephy:dephy@pgbouncer:6432/dephy_worker_registry'
      --nostr-relay "${NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --key "${KEY}"

  poo-pinger:
    image: dephyio/dephy-worker:master
    depends_on:
      - pgbouncer
    environment:
      RUST_LOG: "info,dephy_worker_registry=debug"
      RUST_BACKTRACE: "1"
    entrypoint: "/usr/bin/dephy-worker-registry-poo"
    extra_hosts:
      host.docker.internal: host-gateway
    command: >
      ping
      --forever
      --pg-url 'postgresql://dephy:dephy@pgbouncer:6432/dephy_worker_registry'
      --nostr-relay "${NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --key "${KEY}"

  poo-checker:
    image: dephyio/dephy-worker:master
    depends_on:
      - pgbouncer
    environment:
      RUST_LOG: "info,dephy_worker_registry=debug"
      RUST_BACKTRACE: "1"
    entrypoint: "/usr/bin/dephy-worker-registry-poo"
    extra_hosts:
      host.docker.internal: host-gateway
    command: >
      check
      --forever
      --pg-url 'postgresql://dephy:dephy@pgbouncer:6432/dephy_worker_registry'
      --nostr-relay "${NOSTR_RELAY:-ws://host.docker.internal:8000}"
      --key "${KEY}"

volumes:
  postgresql_data:
