services:
  postgresql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dephy
      POSTGRES_PASSWORD: dephy
      POSTGRES_DB: dephy_worker_registry
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  api:
    image: dephyio/dephy-worker-registry:${DEPHY_IMAGE_TAG:-latest}
    restart: always
    depends_on:
      - postgresql
    environment:
      RUST_LOG: "info,dephy_worker_registry=debug"
      RUST_BACKTRACE: "1"
    entrypoint: "/usr/bin/dephy-worker-registry-api"
    command: >
      --pg-url 'postgresql://dephy:dephy@postgresql:5432/dephy_worker_registry'
      --api-addr '0.0.0.0:9000'
      --worker-nostr-relay "${WORKER_NOSTR_RELAY:-ws://127.0.0.1:8000}"
      --key "${KEY}"
    ports:
      - "0.0.0.0:9000:9000"

volumes:
  postgresql_data:
